### ISSUE TITLE
no protocol: oraclepki.jar

### ISSUE THREAD

**Issue by blakemcbride** [dvare/dynamic-loader#1]
Greetings, and thanks for your dynamic loader!

I have been using it for some time now without any problems.  However, I switched to Zulu 8 (not much more than OpenJDK) and now, when I use your dynamic loader, I get the following error:

[pool-1-thread-2] ERROR org.dvare.dynamic.loader.ClassPathBuilder - no protocol: oraclepki.jar
java.net.MalformedURLException: no protocol: oraclepki.jar
	at java.net.URL.<init>(URL.java:611)
	at java.net.URL.<init>(URL.java:508)
	at java.net.URL.<init>(URL.java:457)
	at org.dvare.dynamic.loader.ClassPathBuilder.getClassPath(ClassPathBuilder.java:53)
	at org.dvare.dynamic.compiler.DynamicCompiler.<init>(DynamicCompiler.java:85)
	at org.dvare.dynamic.compiler.DynamicCompiler.<init>(DynamicCompiler.java:67)
	at org.dvare.dynamic.compiler.DynamicCompiler.<init>(DynamicCompiler.java:63)
	at org.dvare.dynamic.compiler.DynamicCompiler.<init>(DynamicCompiler.java:59)

**Comment by blakemcbride** [comment]
Digging a little deeper, I discovered that eliminating the Oracle JDBC Jar's fixed the problem.  It would be nice if dynamic-loader handled this condition rather than throwing an exception.
